 FROM maven:3.9.4-openjdk-21 AS build
 COPY . .
 RUN mvn clean package -DskipTests

 FROM openjdk:21-slim
 COPY --from=build /target/portfolio-API-0.0.1-SNAPSHOT.jar portfolio-API.jar
 EXPOSE 8080
 ENTRYPOINT ["java","-jar","portfolio-API.jar"]