# Fase di build: utilizziamo un'immagine Maven con OpenJDK 21 per costruire l'applicazione
FROM maven:3.9.4-openjdk-21 AS build

# Copia i file del progetto nella directory di lavoro
WORKDIR /app
COPY . .

# Esegui il comando Maven per costruire il JAR, saltando i test per velocizzare il processo
RUN mvn clean package -DskipTests

# Fase di runtime: utilizziamo un'immagine slim di OpenJDK 21 per eseguire l'app
FROM openjdk:21-slim

# Copia il JAR creato dalla fase di build nella fase di runtime
COPY --from=build /app/target/portfolio-API-0.0.1-SNAPSHOT.jar /app/portfolio-API.jar

# Espone la porta su cui l'applicazione ascolta (di solito 8080)
EXPOSE 8080

# Comando per eseguire l'applicazione Spring Boot
ENTRYPOINT ["java", "-jar", "/app/portfolio-API.jar"]
